swagger: "2.0"
info:
  description: restapi for sigenu
  title: sigapi
  version: 1.0.0
schemes:
- http
paths:
  /students:
    get:
      tags:
        - student
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the students
          schema:
            type: array
            items:
              $ref: "#/definitions/student"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  student:
    type: object
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name: 
        type: string
      middle-name:
        type: string
      last-name:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string