// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetStudentsHandlerFunc turns a function with the right signature into a get students handler
type GetStudentsHandlerFunc func(GetStudentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStudentsHandlerFunc) Handle(params GetStudentsParams) middleware.Responder {
	return fn(params)
}

// GetStudentsHandler interface for that can handle valid get students params
type GetStudentsHandler interface {
	Handle(GetStudentsParams) middleware.Responder
}

// NewGetStudents creates a new http.Handler for the get students operation
func NewGetStudents(ctx *middleware.Context, handler GetStudentsHandler) *GetStudents {
	return &GetStudents{Context: ctx, Handler: handler}
}

/*GetStudents swagger:route GET /students student getStudents

GetStudents get students API

*/
type GetStudents struct {
	Context *middleware.Context
	Handler GetStudentsHandler
}

func (o *GetStudents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetStudentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
